model_name: ../results/meta-llama/Llama-3.1-8B-Instruct/0/checkpoint-400 #meta-llama/Llama-3.1-8B-Instruct #meta-llama/Meta-Llama-3-1B-Instruct #meta-llama/Llama-3.2-1B-Instruct
#model_name: google/gemma-3-4b-it
#model_name: results/checkpoint-9500
# model_name: meta-llama/Llama-2-7b-chat-hf
system_prompt: |
  You are a helpful assistant.
num_reasoning_tokens: 5
multiple_reasoning_tokens: True
#dataset_name: /amazon_review/multi_alpha_dataset_short_llama_3 #_llama_3 #/amazon_review/llama3_multi_alpha_dataset
dataset_name: /amazon_review/multi_alpha_dataset_gemma